# Generated by Django 4.2.5 on 2023-10-02 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConvJobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('excel_file', models.FileField(upload_to='excel_files/')),
                ('conv_file', models.FileField(null=True, upload_to='conv_files/')),
                ('conv_at', models.DateTimeField(auto_now_add=True)),
                ('error', models.CharField(max_length=300, null=True)),
                ('success', models.BooleanField(default=False)),
            ],
        ),
    ]
