# Generated by Django 4.2.5 on 2023-10-02 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('excel_conv', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ConvJobs',
            new_name='ConvJob',
        ),
    ]
