# Generated by Django 4.2.5 on 2023-10-02 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excel_conv', '0002_rename_convjobs_convjob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='convjob',
            name='conv_file',
            field=models.FileField(blank=True, null=True, upload_to='conv_files/'),
        ),
        migrations.AlterField(
            model_name='convjob',
            name='error',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
