# Generated by Django 4.2.5 on 2023-10-04 14:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('excel_conv', '0003_alter_convjob_conv_file_alter_convjob_error'),
    ]

    operations = [
        migrations.AddField(
            model_name='convjob',
            name='upload_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='convjob',
            name='conv_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
