# Generated by Django 4.2.5 on 2023-10-04 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excel_conv', '0004_convjob_upload_at_alter_convjob_conv_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='convjob',
            name='upload_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
